In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
import pandas as pd
import numpy as np

In [2]:
consumers = pd.read_parquet("data/consumers.pqt")

In [3]:
consumers

      prism_consumer_id evaluation_date  credit_score  DQ_TARGET
0                     0      2021-09-01         726.0        0.0
1                     1      2021-07-01         626.0        0.0
2                     2      2021-05-01         680.0        0.0
3                     3      2021-03-01         734.0        0.0
4                     4      2021-10-01         676.0        0.0
...                 ...             ...           ...        ...
14995             14995      2022-03-08         655.0        NaN
14996             14996      2022-01-15         625.0        NaN
14997             14997      2022-01-31         688.0        NaN
14998             14998      2022-03-08         722.0        NaN
14999             14999      2022-02-12         751.0        NaN

[15000 rows x 4 columns]

In [4]:
transactions = pd.read_parquet("data/transactions.pqt")

In [5]:
transactions

,prism_consumer_id,prism_transaction_id,category,amount,credit_or_debit,posted_date
0,3023,0,4,0.05,CREDIT,1618531200000000000
1,3023,1,12,481.56,CREDIT,1619740800000000000
2,3023,2,4,0.05,CREDIT,1621123200000000000
3,3023,3,4,0.07,CREDIT,1623801600000000000
4,3023,4,4,0.06,CREDIT,1626393600000000000
...,...,...,...,...,...,...
6407316,10533,6405304,31,4.96,DEBIT,1646956800000000000
6407317,10533,6405305,12,63.48,DEBIT,1648598400000000000
6407318,10533,6405306,12,53.99,DEBIT,1648598400000000000
6407319,10533,6405307,12,175.98,DEBIT,1648684800000000000
6407320,10533,6405308,14,16.04,DEBIT,1648684800000000000

In [6]:
accounts = pd.read_parquet("data/accounts.pqt")

In [7]:
accounts

,prism_consumer_id,prism_account_id,account_type,balance_date,balance
0,3023,0,SAVINGS,1630368000000000000,90.57
1,3023,1,CHECKING,1630368000000000000,225.95
2,4416,2,SAVINGS,1648684800000000000,15157.17
3,4416,3,CHECKING,1648684800000000000,66.42
4,4227,4,CHECKING,1627689600000000000,7042.90
...,...,...,...,...,...
24461,11500,24461,CHECKING,1648339200000000000,732.75
24462,11615,24462,SAVINGS,1648598400000000000,5.00
24463,11615,24463,CHECKING,1648598400000000000,1956.46
24464,12210,24464,CHECKING,1648425600000000000,2701.51
24465,11615,24465,CHECKING,1648598400000000000,7967.45

In [8]:
categories = pd.read_csv("data/catmap.csv")

In [9]:
categories.set_index('category_id')

                          category
category_id
0                    SELF_TRANSFER
1                EXTERNAL_TRANSFER
2                          DEPOSIT
3                         PAYCHECK
4                    MISCELLANEOUS
5             PAYCHECK_PLACEHOLDER
6                           REFUND
7                INVESTMENT_INCOME
8                   OTHER_BENEFITS
9            UNEMPLOYMENT_BENEFITS
10            SMALL_DOLLAR_ADVANCE
11                             TAX
12                            LOAN
13                       INSURANCE
14              FOOD_AND_BEVERAGES
15                   UNCATEGORIZED
16             GENERAL_MERCHANDISE
17                      AUTOMOTIVE
18                       GROCERIES
19                        ATM_CASH
20                   ENTERTAINMENT
21                          TRAVEL
22              ESSENTIAL_SERVICES
23                    ACCOUNT_FEES
24                HOME_IMPROVEMENT
25                       OVERDRAFT
26             CREDIT_CARD_PAYMENT
27              HEALTHCARE_MEDICAL
28                            PETS
29                       EDUCATION
30                 GIFTS_DONATIONS
31                 BILLS_UTILITIES
32                        MORTGAGE
33                CHILD_DEPENDENTS
34                            RENT
35                            BNPL
36                       AUTO_LOAN
37               BANKING_CATCH_ALL
38                            DEBT
39                         FITNESS
40                   TRANSPORATION
41                           LEGAL
42             GOVERNMENT_SERVICES
43                  RISK_CATCH_ALL
44                         RTO_LTO
45                      INVESTMENT
46                        GAMBLING
47              CORPORATE_PAYMENTS
48                   TIME_OR_STUFF
49                         PENSION

### Income/Balance Features

In [10]:
income_cats = [2, 3, 7, 8, 9, 49]

In [11]:
income_trxns = transactions[transactions['category'].isin(income_cats)].copy()

In [12]:
income_trxns['posted_date'] = pd.to_datetime(income_trxns['posted_date'])

In [13]:
monthly_income = income_trxns.groupby(['prism_consumer_id', income_trxns['posted_date'].dt.to_period('M')])['amount'].sum()

In [14]:
avg_monthly_income = monthly_income.groupby('prism_consumer_id').mean().rename('avg_monthly_income')

In [15]:
avg_monthly_income

prism_consumer_id
0       1331.508571
1       1915.941429
10      2202.962857
100     4068.630000
1000    6911.228571
           ...
9995    3742.280000
9996       0.010000
9997    4168.215000
9998    2401.076667
9999    4185.220000
Name: avg_monthly_income, Length: 13878, dtype: float64

In [16]:
income_std = monthly_income.groupby('prism_consumer_id').std().rename('income_std')

In [17]:
income_std

prism_consumer_id
0        723.657216
1        621.198567
10       958.152740
100      949.527857
1000    3141.124869
           ...
9995     918.977561
9996       0.000000
9997    1891.170898
9998     104.801560
9999    2853.394063
Name: income_std, Length: 13878, dtype: float64

In [18]:
avg_balance = accounts.groupby('prism_consumer_id')['balance'].mean().rename('avg_balance')

In [19]:
avg_balance

prism_consumer_id
0        160.185
1       1651.210
10       412.120
100     1327.735
1000      47.625
          ...
9995       0.000
9996     252.670
9997     611.280
9998    -862.990
9999      -9.020
Name: avg_balance, Length: 13009, dtype: float64

In [20]:
features = pd.DataFrame(index=consumers['prism_consumer_id'].unique())
features = features.join([avg_monthly_income, income_std, avg_balance])

In [21]:
features['balance_income_ratio'] = features['avg_balance'] / (features['avg_monthly_income'])

In [22]:
features['prism_consumer_id'] = features.index

### Category Features

In [23]:
neg_cats = [25, 10, 46, 23] # OVERDRAFT, SMALL_DOLLAR_ADVANCE, GAMBLING, ACCOUNT_FEES

In [24]:
neg_trxns = transactions[transactions['category'].isin(neg_cats)].copy()
neg_trxns['posted_date'] = pd.to_datetime(neg_trxns['posted_date'])

In [25]:
monthly_neg_count = neg_trxns.groupby(['prism_consumer_id', neg_trxns['posted_date'].dt.to_period('M')])['amount'].count().reset_index()

In [26]:
avg_monthly_neg_count = monthly_neg_count.groupby('prism_consumer_id')['amount'].mean().rename('avg_monthly_neg_count')

In [27]:
total_neg_amount = neg_trxns.groupby('prism_consumer_id')['amount'].sum().rename('total_neg_amount')

In [28]:
has_neg = neg_trxns.groupby('prism_consumer_id')['amount'].any().astype(int).rename('has_neg')

In [29]:
features = features.join([avg_monthly_neg_count, total_neg_amount, has_neg])

In [30]:
features[features.isna()] = 0

In [31]:
features

,avg_monthly_income,income_std,avg_balance,balance_income_ratio,prism_consumer_id,avg_monthly_neg_count,total_neg_amount,has_neg
0,1331.508571,723.657216,160.185,0.120303,0,0.000000,0.00,0.0
1,1915.941429,621.198567,1651.210,0.861827,1,0.000000,0.00,0.0
2,550.000000,636.396103,1402.680,2.550327,2,0.000000,0.00,0.0
3,2155.562000,2768.113331,3833.505,1.778425,3,0.000000,0.00,0.0
4,1724.920000,949.138545,197.275,0.114368,4,5.000000,495.98,1.0
...,...,...,...,...,...,...,...,...
14995,2323.835000,623.490298,0.000,0.000000,14995,0.000000,0.00,0.0
14996,3504.064444,3370.822540,3410.960,0.973430,14996,2.125000,102.10,1.0
14997,2892.746250,556.164692,0.000,0.000000,14997,1.500000,52.00,1.0
14998,6847.975000,1771.276101,0.000,0.000000,14998,4.428571,815.78,1.0
14999,1513.232222,776.449958,2000.940,1.322295,14999,0.000000,0.00,0.0

In [32]:
df = consumers.merge(features, on='prism_consumer_id')

In [33]:
df = df[~df['DQ_TARGET'].isnull()]

In [34]:
df

,prism_consumer_id,evaluation_date,credit_score,DQ_TARGET,avg_monthly_income,income_std,avg_balance,balance_income_ratio,avg_monthly_neg_count,total_neg_amount,has_neg
0,0,2021-09-01,726.0,0.0,1331.508571,723.657216,160.185000,0.120303,0.000000,0.00,0.0
1,1,2021-07-01,626.0,0.0,1915.941429,621.198567,1651.210000,0.861827,0.000000,0.00,0.0
2,2,2021-05-01,680.0,0.0,550.000000,636.396103,1402.680000,2.550327,0.000000,0.00,0.0
3,3,2021-03-01,734.0,0.0,2155.562000,2768.113331,3833.505000,1.778425,0.000000,0.00,0.0
4,4,2021-10-01,676.0,0.0,1724.920000,949.138545,197.275000,0.114368,5.000000,495.98,1.0
...,...,...,...,...,...,...,...,...,...,...,...
13995,13995,2022-01-22,802.0,0.0,0.278750,0.138918,342.933333,1230.254111,0.000000,0.00,0.0
13996,13996,2022-02-01,652.0,0.0,1687.030000,1880.778971,1642.252857,0.973458,1.777778,238.95,1.0
13997,13997,2021-12-24,765.0,0.0,749.562857,1136.546514,1198.425000,1.598832,0.000000,0.00,0.0
13998,13998,2022-01-30,685.0,0.0,4184.258750,4473.856723,2967.142000,0.709120,0.000000,0.00,0.0
13999,13999,2022-01-26,653.0,0.0,4076.742500,2193.855255,-20.500000,-0.005029,5.555556,1730.00,1.0

In [35]:
for col in features.drop(columns=['prism_consumer_id']):
    X = df[[col]]
    y = df['DQ_TARGET']
    
    model = LogisticRegression()
    model.fit(X, y)
    
    preds = model.predict_proba(X)[:, 1]
    
    score = roc_auc_score(y, preds)

    print(col)
    print(score)

avg_monthly_income
0.5467276837429127
income_std
0.5265585855433164
avg_balance
0.6649332674138904
balance_income_ratio
0.638123415229923
avg_monthly_neg_count
0.6006387995476296
total_neg_amount
0.5960169942686975
has_neg
0.5862211667235083

In [36]:
consumers.dropna(subset=['DQ_TARGET'])

      prism_consumer_id evaluation_date  credit_score  DQ_TARGET
0                     0      2021-09-01         726.0        0.0
1                     1      2021-07-01         626.0        0.0
2                     2      2021-05-01         680.0        0.0
3                     3      2021-03-01         734.0        0.0
4                     4      2021-10-01         676.0        0.0
...                 ...             ...           ...        ...
13995             13995      2022-01-22         802.0        0.0
13996             13996      2022-02-01         652.0        0.0
13997             13997      2021-12-24         765.0        0.0
13998             13998      2022-01-30         685.0        0.0
13999             13999      2022-01-26         653.0        0.0

[12000 rows x 4 columns]

In [37]:
df = pd.read_csv('data/model_scores.csv')

In [38]:
df.groupby('model')['test_auc'].max().sort_values(ascending=False)

model
xgboost     0.773567
log-reg     0.766369
catboost    0.763502
lightgbm    0.762106
Name: test_auc, dtype: float64

In [39]:
model_scores = pd.read_csv('data/model_scores.csv')

In [40]:
model_scores

,model,train_auc,test_auc,train_time,device,tune_time,cv_auc,n_trials,date
0,log-reg,0.885825,0.656276,3.246427,CPU,0.000000,0.000000,0,2026-02-14 08:11:04.097346
1,xgboost,0.997695,0.712361,4.918420,CPU,0.000000,0.000000,0,2026-02-14 08:11:09.028058
2,catboost,0.975549,0.763502,38.326673,CPU,0.000000,0.000000,0,2026-02-14 08:11:47.365748
3,lightgbm,0.993716,0.741894,3.471492,CPU,0.000000,0.000000,0,2026-02-14 08:11:50.854401
4,lightgbm,0.842186,0.762106,1385.430531,CPU,1385.320979,0.780578,100,2026-02-16 02:59:22.062535
5,catboost,0.959545,0.760960,11974.164480,CPU,11974.058786,0.781882,100,2026-02-16 06:24:05.885515
6,xgboost,0.940515,0.773567,38979.357312,CPU,38979.236512,0.783594,100,2026-02-19 15:46:58.540255
7,log-reg,0.885825,0.656276,3.325073,CPU,0.000000,0.000000,0,2026-02-21 23:17:30.915084
8,log-reg,0.958300,0.572133,1.469458,CPU,0.000000,0.000000,0,2026-02-21 23:21:32.828315
9,log-reg,0.988911,0.605144,5.546234,CPU,0.000000,0.000000,0,2026-02-21 23:25:02.263715
10,log-reg,0.787013,0.766369,68.351219,GPU/CPU,0.000000,0.000000,0,2026-03-08 18:41:35.205926